#include "bsp_seven_seg.h"

#if CONFIG_MODULE_SEVEN_SEG

void seven_seg_num_clear(void)
{
        CONFIG_SEVEN_SEG_GPIO_PORT->BSRR = CONFIG_SEVEN_SEG_A_GPIO_PIN | CONFIG_SEVEN_SEG_B_GPIO_PIN | CONFIG_SEVEN_SEG_C_GPIO_PIN | CONFIG_SEVEN_SEG_D_GPIO_PIN | CONFIG_SEVEN_SEG_E_GPIO_PIN | CONFIG_SEVEN_SEG_F_GPIO_PIN | CONFIG_SEVEN_SEG_G_GPIO_PIN;
}


void seven_seg_set_num_0(void)
{
        CONFIG_SEVEN_SEG_GPIO_PORT->BSRR = CONFIG_SEVEN_SEG_A_GPIO_PIN | CONFIG_SEVEN_SEG_B_GPIO_PIN | CONFIG_SEVEN_SEG_C_GPIO_PIN | CONFIG_SEVEN_SEG_D_GPIO_PIN | CONFIG_SEVEN_SEG_E_GPIO_PIN | CONFIG_SEVEN_SEG_F_GPIO_PIN;
        CONFIG_SEVEN_SEG_GPIO_PORT->BRR = CONFIG_SEVEN_SEG_G_GPIO_PIN;
}


void seven_seg_set_num_1(void)
{
        CONFIG_SEVEN_SEG_GPIO_PORT->BSRR = CONFIG_SEVEN_SEG_B_GPIO_PIN | CONFIG_SEVEN_SEG_C_GPIO_PIN;
        CONFIG_SEVEN_SEG_GPIO_PORT->BRR = CONFIG_SEVEN_SEG_A_GPIO_PIN | CONFIG_SEVEN_SEG_D_GPIO_PIN | CONFIG_SEVEN_SEG_E_GPIO_PIN | CONFIG_SEVEN_SEG_F_GPIO_PIN | CONFIG_SEVEN_SEG_G_GPIO_PIN;
}


void seven_seg_set_num_2(void)
{
        CONFIG_SEVEN_SEG_GPIO_PORT->BSRR = CONFIG_SEVEN_SEG_A_GPIO_PIN | CONFIG_SEVEN_SEG_B_GPIO_PIN   | CONFIG_SEVEN_SEG_D_GPIO_PIN | CONFIG_SEVEN_SEG_E_GPIO_PIN   | CONFIG_SEVEN_SEG_G_GPIO_PIN;
        CONFIG_SEVEN_SEG_GPIO_PORT->BRR = CONFIG_SEVEN_SEG_C_GPIO_PIN | CONFIG_SEVEN_SEG_F_GPIO_PIN;
}

void seven_seg_set_num_3(void)
{
        CONFIG_SEVEN_SEG_GPIO_PORT->BSRR = CONFIG_SEVEN_SEG_A_GPIO_PIN | CONFIG_SEVEN_SEG_B_GPIO_PIN | CONFIG_SEVEN_SEG_C_GPIO_PIN | CONFIG_SEVEN_SEG_D_GPIO_PIN     | CONFIG_SEVEN_SEG_G_GPIO_PIN;
        CONFIG_SEVEN_SEG_GPIO_PORT->BRR = CONFIG_SEVEN_SEG_E_GPIO_PIN | CONFIG_SEVEN_SEG_F_GPIO_PIN;
}


void seven_seg_set_num_4(void)
{
        CONFIG_SEVEN_SEG_GPIO_PORT->BSRR = CONFIG_SEVEN_SEG_B_GPIO_PIN | CONFIG_SEVEN_SEG_C_GPIO_PIN | CONFIG_SEVEN_SEG_F_GPIO_PIN | CONFIG_SEVEN_SEG_G_GPIO_PIN;
        CONFIG_SEVEN_SEG_GPIO_PORT->BRR = CONFIG_SEVEN_SEG_A_GPIO_PIN | CONFIG_SEVEN_SEG_D_GPIO_PIN | CONFIG_SEVEN_SEG_E_GPIO_PIN;
}


void seven_seg_set_num_5(void)
{
        CONFIG_SEVEN_SEG_GPIO_PORT->BSRR = CONFIG_SEVEN_SEG_A_GPIO_PIN  | CONFIG_SEVEN_SEG_C_GPIO_PIN | CONFIG_SEVEN_SEG_D_GPIO_PIN   | CONFIG_SEVEN_SEG_F_GPIO_PIN | CONFIG_SEVEN_SEG_G_GPIO_PIN;
        CONFIG_SEVEN_SEG_GPIO_PORT->BRR = CONFIG_SEVEN_SEG_B_GPIO_PIN | CONFIG_SEVEN_SEG_E_GPIO_PIN;
}


void seven_seg_set_num_6(void)
{
        CONFIG_SEVEN_SEG_GPIO_PORT->BSRR = CONFIG_SEVEN_SEG_A_GPIO_PIN  | CONFIG_SEVEN_SEG_C_GPIO_PIN | CONFIG_SEVEN_SEG_D_GPIO_PIN | CONFIG_SEVEN_SEG_E_GPIO_PIN | CONFIG_SEVEN_SEG_F_GPIO_PIN | CONFIG_SEVEN_SEG_G_GPIO_PIN;
        CONFIG_SEVEN_SEG_GPIO_PORT->BRR = CONFIG_SEVEN_SEG_B_GPIO_PIN;
}


void seven_seg_set_num_7(void)
{
        CONFIG_SEVEN_SEG_GPIO_PORT->BSRR = CONFIG_SEVEN_SEG_A_GPIO_PIN | CONFIG_SEVEN_SEG_B_GPIO_PIN | CONFIG_SEVEN_SEG_C_GPIO_PIN;
        CONFIG_SEVEN_SEG_GPIO_PORT->BRR = CONFIG_SEVEN_SEG_D_GPIO_PIN | CONFIG_SEVEN_SEG_E_GPIO_PIN | CONFIG_SEVEN_SEG_F_GPIO_PIN | CONFIG_SEVEN_SEG_G_GPIO_PIN;
}


void seven_seg_set_num_8(void)
{
        CONFIG_SEVEN_SEG_GPIO_PORT->BSRR = CONFIG_SEVEN_SEG_A_GPIO_PIN | CONFIG_SEVEN_SEG_B_GPIO_PIN | CONFIG_SEVEN_SEG_C_GPIO_PIN | CONFIG_SEVEN_SEG_D_GPIO_PIN | CONFIG_SEVEN_SEG_E_GPIO_PIN | CONFIG_SEVEN_SEG_F_GPIO_PIN | CONFIG_SEVEN_SEG_G_GPIO_PIN;
}


void seven_seg_set_num_9(void)
{
        CONFIG_SEVEN_SEG_GPIO_PORT->BSRR = CONFIG_SEVEN_SEG_A_GPIO_PIN | CONFIG_SEVEN_SEG_B_GPIO_PIN | CONFIG_SEVEN_SEG_C_GPIO_PIN | CONFIG_SEVEN_SEG_D_GPIO_PIN     | CONFIG_SEVEN_SEG_F_GPIO_PIN | CONFIG_SEVEN_SEG_G_GPIO_PIN;
        CONFIG_SEVEN_SEG_GPIO_PORT->BRR = CONFIG_SEVEN_SEG_E_GPIO_PIN;
}


void seven_seg_set_num_blank(void)
{
        CONFIG_SEVEN_SEG_GPIO_PORT->BRR = CONFIG_SEVEN_SEG_A_GPIO_PIN | CONFIG_SEVEN_SEG_B_GPIO_PIN | CONFIG_SEVEN_SEG_C_GPIO_PIN | CONFIG_SEVEN_SEG_D_GPIO_PIN | CONFIG_SEVEN_SEG_E_GPIO_PIN | CONFIG_SEVEN_SEG_F_GPIO_PIN | CONFIG_SEVEN_SEG_G_GPIO_PIN;
}


void seven_seg_set_cs_0(void)
{
        CONFIG_SEVEN_SEG_CS_GPIO_PORT->BRR = CONFIG_SEVEN_SEG_CS1_GPIO_PIN | CONFIG_SEVEN_SEG_CS2_GPIO_PIN | CONFIG_SEVEN_SEG_CS3_GPIO_PIN | CONFIG_SEVEN_SEG_CS4_GPIO_PIN;
}


void seven_seg_set_cs_1(void)
{
        CONFIG_SEVEN_SEG_CS_GPIO_PORT->BRR =    CONFIG_SEVEN_SEG_CS2_GPIO_PIN | CONFIG_SEVEN_SEG_CS3_GPIO_PIN | CONFIG_SEVEN_SEG_CS4_GPIO_PIN;
        CONFIG_SEVEN_SEG_CS_GPIO_PORT->BSRR = CONFIG_SEVEN_SEG_CS1_GPIO_PIN;
}


void seven_seg_set_cs_2(void)
{
        CONFIG_SEVEN_SEG_CS_GPIO_PORT->BRR =  CONFIG_SEVEN_SEG_CS1_GPIO_PIN    | CONFIG_SEVEN_SEG_CS3_GPIO_PIN | CONFIG_SEVEN_SEG_CS4_GPIO_PIN;
        CONFIG_SEVEN_SEG_CS_GPIO_PORT->BSRR = CONFIG_SEVEN_SEG_CS2_GPIO_PIN;
}


void seven_seg_set_cs_3(void)
{
        CONFIG_SEVEN_SEG_CS_GPIO_PORT->BRR =    CONFIG_SEVEN_SEG_CS3_GPIO_PIN | CONFIG_SEVEN_SEG_CS4_GPIO_PIN;
        CONFIG_SEVEN_SEG_CS_GPIO_PORT->BSRR = CONFIG_SEVEN_SEG_CS1_GPIO_PIN | CONFIG_SEVEN_SEG_CS2_GPIO_PIN;
}


void seven_seg_set_cs_4(void)
{
        CONFIG_SEVEN_SEG_CS_GPIO_PORT->BRR =    CONFIG_SEVEN_SEG_CS1_GPIO_PIN | CONFIG_SEVEN_SEG_CS2_GPIO_PIN    | CONFIG_SEVEN_SEG_CS4_GPIO_PIN;
        CONFIG_SEVEN_SEG_CS_GPIO_PORT->BSRR = CONFIG_SEVEN_SEG_CS3_GPIO_PIN;
}


void seven_seg_set_cs_5(void)
{
        CONFIG_SEVEN_SEG_CS_GPIO_PORT->BRR =    CONFIG_SEVEN_SEG_CS2_GPIO_PIN    | CONFIG_SEVEN_SEG_CS4_GPIO_PIN;
        CONFIG_SEVEN_SEG_CS_GPIO_PORT->BSRR = CONFIG_SEVEN_SEG_CS3_GPIO_PIN | CONFIG_SEVEN_SEG_CS1_GPIO_PIN;
}


void seven_seg_set_cs_6(void)
{
        CONFIG_SEVEN_SEG_CS_GPIO_PORT->BRR =    CONFIG_SEVEN_SEG_CS1_GPIO_PIN    | CONFIG_SEVEN_SEG_CS4_GPIO_PIN;
        CONFIG_SEVEN_SEG_CS_GPIO_PORT->BSRR = CONFIG_SEVEN_SEG_CS3_GPIO_PIN | CONFIG_SEVEN_SEG_CS2_GPIO_PIN;
}


void seven_seg_set_cs_7(void)
{
        CONFIG_SEVEN_SEG_CS_GPIO_PORT->BRR =    CONFIG_SEVEN_SEG_CS4_GPIO_PIN;
        CONFIG_SEVEN_SEG_CS_GPIO_PORT->BSRR = CONFIG_SEVEN_SEG_CS3_GPIO_PIN | CONFIG_SEVEN_SEG_CS2_GPIO_PIN | CONFIG_SEVEN_SEG_CS1_GPIO_PIN;
}


void seven_seg_set_cs_8(void)
{
        CONFIG_SEVEN_SEG_CS_GPIO_PORT->BRR =    CONFIG_SEVEN_SEG_CS3_GPIO_PIN | CONFIG_SEVEN_SEG_CS2_GPIO_PIN | CONFIG_SEVEN_SEG_CS1_GPIO_PIN;
        CONFIG_SEVEN_SEG_CS_GPIO_PORT->BSRR = CONFIG_SEVEN_SEG_CS4_GPIO_PIN;
}


void seven_seg_set_cs_9(void)
{
        CONFIG_SEVEN_SEG_CS_GPIO_PORT->BRR =    CONFIG_SEVEN_SEG_CS3_GPIO_PIN | CONFIG_SEVEN_SEG_CS2_GPIO_PIN;
        CONFIG_SEVEN_SEG_CS_GPIO_PORT->BSRR = CONFIG_SEVEN_SEG_CS4_GPIO_PIN | CONFIG_SEVEN_SEG_CS1_GPIO_PIN;
}


SEVEN_SEG_SET_NUM_FUNC seven_seg_set_num_func[12] = {
        seven_seg_set_num_0,
        seven_seg_set_num_1,
        seven_seg_set_num_2,
        seven_seg_set_num_3,
        seven_seg_set_num_4,
        seven_seg_set_num_5,
        seven_seg_set_num_6,
        seven_seg_set_num_7,
        seven_seg_set_num_8,
        seven_seg_set_num_9,
        seven_seg_set_num_blank,
        seven_seg_num_clear,
};


SEVEN_SEG_SET_NUM_FUNC seven_seg_set_cs_func[10] = {
        seven_seg_set_cs_0,
        seven_seg_set_cs_1,
        seven_seg_set_cs_2,
        seven_seg_set_cs_3,
        seven_seg_set_cs_4,
        seven_seg_set_cs_5,
        seven_seg_set_cs_6,
        seven_seg_set_cs_7,
        seven_seg_set_cs_8,
        seven_seg_set_cs_9,
};


SEVEN_SEG_SET_NUM_FUNC *seven_seg_num_func_get(void)
{
        return &(seven_seg_set_num_func[0]);
}


SEVEN_SEG_CS_FUNC *seven_seg_cs_func_get(void)
{
        return &(seven_seg_set_cs_func[0]);
}


static void nvic_config(void)
{
        NVIC_InitTypeDef init;

        init.NVIC_IRQChannel = CONFIG_SEVEN_SEG_TIM_IRQ;
        init.NVIC_IRQChannelPreemptionPriority = CONFIG_SEVEN_SET_TIM_IRQ_PRIO;
        init.NVIC_IRQChannelSubPriority = 0;
        init.NVIC_IRQChannelCmd = ENABLE;

        NVIC_Init(&init);
}

void seven_seg_init(void)
{
        GPIO_InitTypeDef gpio_init;
        TIM_TimeBaseInitTypeDef tim_init;

        CONFIG_SEVEN_SEG_CLK_FUN(CONFIG_SEVEN_SEG_CLK, ENABLE);
        CONFIG_SEVEN_SEG_SCAN_TIM_CLK_FUN(CONFIG_SEVEN_SEG_SCAN_TIM_CLK, ENABLE);
        CONFIG_SEVEN_SEG_CS_CLK_FUN(CONFIG_SEVEN_SEG_CS_CLK, ENABLE);
        CONFIG_SEVEN_SEG_TIM_CLK_FUN(CONFIG_SEVEN_SEG_TIM_CLK, ENABLE);

        // Disable JTAG
        GPIO_PinRemapConfig(GPIO_Remap_SWJ_JTAGDisable, ENABLE);

        gpio_init.GPIO_Pin = CONFIG_SEVEN_SEG_A_GPIO_PIN | CONFIG_SEVEN_SEG_B_GPIO_PIN | CONFIG_SEVEN_SEG_C_GPIO_PIN | CONFIG_SEVEN_SEG_D_GPIO_PIN | CONFIG_SEVEN_SEG_E_GPIO_PIN | CONFIG_SEVEN_SEG_F_GPIO_PIN | CONFIG_SEVEN_SEG_G_GPIO_PIN;
        gpio_init.GPIO_Mode = GPIO_Mode_Out_PP;
        gpio_init.GPIO_Speed = GPIO_Speed_50MHz;
        GPIO_Init(CONFIG_SEVEN_SEG_GPIO_PORT, &gpio_init);

        gpio_init.GPIO_Pin = CONFIG_SEVEN_SEG_CS1_GPIO_PIN | CONFIG_SEVEN_SEG_CS2_GPIO_PIN | CONFIG_SEVEN_SEG_CS3_GPIO_PIN | CONFIG_SEVEN_SEG_CS4_GPIO_PIN;
        gpio_init.GPIO_Mode = GPIO_Mode_Out_PP;
        gpio_init.GPIO_Speed = GPIO_Speed_50MHz;
        GPIO_Init(CONFIG_SEVEN_SEG_CS_GPIO_PORT, &gpio_init);

        tim_init.TIM_Period = 1000 - 1;
        tim_init.TIM_Prescaler = 71;
        TIM_TimeBaseInit(CONFIG_SEVEN_SEG_TIM, &tim_init);

        TIM_ClearFlag(CONFIG_SEVEN_SEG_TIM, TIM_FLAG_Update);
        TIM_ITConfig(CONFIG_SEVEN_SEG_TIM, TIM_IT_Update, ENABLE);

        nvic_config();

        TIM_Cmd(CONFIG_SEVEN_SEG_TIM, ENABLE);
}

#endif /* CONFIG_MODULE_SEVEN_SEG */

